apps/home/urls.py
from django.urls import path, include
from apps.home.views import (
    Home,
    Login,
    DetailProfile,
    NewPost,
    EditPost,
    DeletePost,
    DeleteProfile,
    Subscriptions,
    Unsubscriptions
)
from django.views.generic import TemplateView
from apps.article.views import DetailArticle
from apps.comments.views import DeleteComments

app_name = 'home'

urlpatterns = [
    path('deletecomment/<int:pk>/', DeleteComments.as_view(), name='delete_comment'),
    path('detailarticle/<int:pk>/', DetailArticle.as_view(), name='detail_article'),
    path('unsubscriptions/<int:pk>/', Unsubscriptions.as_view(), name='unsubscriptions_page'),
    path('subscriptions/<int:pk>/', Subscriptions.as_view(), name='subscriptions_page'),
    path('profile/id<int:pk>/', DetailProfile.as_view(), name='detail_profile'),
    path('editpost/<int:pk>/', EditPost.as_view(), name='edit_post'),
    path('deleteprofile/<int:pk>/', DeleteProfile.as_view(), name='delete_profile'),
    path('deletepost/<int:pk>/', DeletePost.as_view(), name='delete_post'),
    path('younewpost/', NewPost.as_view(), name='newpost_page'),
    path('login/', Login.as_view(), name='login_page'),
    path('about/', TemplateView.as_view(template_name="home/about.html"), name='about'),
    path('contact/', TemplateView.as_view(template_name="home/contact.html"), name='contact'),
    path('', Home.as_view(), name='home_page'),
]

apps/search/urls.py
from django.urls import path
from apps.search.views import Search

app_name = 'search'


urlpatterns = [
    path('', Search.as_view(), name='search_page'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('notes/', include('apps.notes.urls', namespace='notes')),
    path('search/', include('apps.search.urls', namespace='search')),
    path('admin/', admin.site.urls),
    path('settings/', include('apps.settings_profile.urls', namespace='settings')),
    path('registration/', include('apps.Profile.urls', namespace='profile')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/search/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.db.models import Q
from apps.article.models import Article
from django.contrib.auth.models import User

# Create your views here.
class Search(View):

    ''' Search view '''

    def get(self, request, *args, **kwargs):
        query = request.GET.get('q')
        if query:
            articles = Article.objects.filter(
                Q(text__icontains=query) |
                Q(text__startswith=query) |
                Q(text__istartswith=query) |
                Q(text__endswith=query) |
                Q(text__iendswith=query)
            )
            users = User.objects.filter(
                Q(first_name__icontains=query) |
                Q(first_name__startswith=query) |
                Q(first_name__istartswith=query) |
                Q(first_name__endswith=query) |
                Q(first_name__iendswith=query) |
                Q(last_name__icontains=query) |
                Q(last_name__startswith=query) |
                Q(last_name__istartswith=query) |
                Q(last_name__endswith=query) |
                Q(last_name__iendswith=query)

            )
            return render(request, 'search/search.html', {'articles': articles, 'users': users})
        return redirect('home:home_page')

apps/templates/search/search.html
{% extends 'base.html' %}


{% block content %}
{% include 'header.html' %}

<div class="search_result">
    <div class="search_title">
        <h3>RESULT</h3>
    </div>
    {% if articles %}
        {% for article in articles %}
        <div class="article_main">
            {% if user == article.author %}
            <div class="delete_edit_post">
                <a href="{% url 'home:edit_post' pk=article.pk %}">edit</a>
                <a class="delete_btn" href="{% url 'home:delete_post' pk=article.pk %}">delete</a>
            </div>
            {% endif %}
            <div class="article_info_user">
                {% if article.author.profile.avatar %}
                    <img src="{{article.author.profile.avatar.url}}" width="40px" height="40px" />
                {% else %}
                    <img src="https://www.freeiconspng.com/uploads/no-image-icon-4.png" width="40px" height="40px" />
                {% endif %}
                <a href="{% url 'home:detail_profile' pk=article.author.profile.pk %}">{{article.author.profile.fullname}}</a>
                <span>{{article.date|date:'m-d H:i'}}</span>
            </div>
            {% if article.img %}
                <div class="img_article">
                    <img src="{{article.img.url}}" />
                </div>
            {% endif %}
            <p>{{article.text}} <a class="show_view" href="{% url 'home:detail_article' pk=article.pk %}">show view</a></p>
            <p class="comments">comments : <span class="count_comments_class">{{article.count_comments}}</span></p>
        </div>
        {% endfor %}
        {% if users %}

        {% for user in users %}
            <div class="search_user">
                <div class="div_user_info">
                {% if user.profile.avatar %}
                    <img src="{{user.profile.avatar.url}}" width="50px" height="50px" />
                {% else %}
                    <img src="https://www.freeiconspng.com/uploads/no-image-icon-4.png" width="50px" height="50px" />
                {% endif %}
                <a href="{% url 'home:detail_profile' pk=user.profile.pk %}">{{user.profile.fullname}}</a>
                <span>{{user.profile.description}}</span>
                </div>
            </div>
        {% endfor %}

        {% endif %}
    {% elif users %}
        {% for user in users %}
            <div class="search_user">
                <div class="div_user_info">
                {% if user.profile.avatar %}
                    <img src="{{user.profile.avatar.url}}" width="50px" height="50px" />
                {% else %}
                    <img src="https://www.freeiconspng.com/uploads/no-image-icon-4.png" width="50px" height="50px" />
                {% endif %}
                <a href="{% url 'home:detail_profile' pk=user.profile.pk %}">{{user.profile.fullname}}</a>
                <span>{{user.profile.description}}</span>
                </div>
            </div>
        {% endfor %}
    {% else %}
        <div class="not_found_search">
            <p> No results found for your request. </p>
        </div>
    {% endif %}


</div>

{% endblock %}