apps/home/urls.py
from django.urls import path, include
from apps.home.views import (
    Home,
    Login,
    DetailProfile,
    NewPost,
    EditPost,
    DeletePost,
    DeleteProfile,
    Subscriptions,
    Unsubscriptions
)
from django.views.generic import TemplateView
from apps.article.views import DetailArticle
from apps.comments.views import DeleteComments

app_name = 'home'

urlpatterns = [
    path('deletecomment/<int:pk>/', DeleteComments.as_view(), name='delete_comment'),
    path('detailarticle/<int:pk>/', DetailArticle.as_view(), name='detail_article'),
    path('unsubscriptions/<int:pk>/', Unsubscriptions.as_view(), name='unsubscriptions_page'),
    path('subscriptions/<int:pk>/', Subscriptions.as_view(), name='subscriptions_page'),
    path('profile/id<int:pk>/', DetailProfile.as_view(), name='detail_profile'),
    path('editpost/<int:pk>/', EditPost.as_view(), name='edit_post'),
    path('deleteprofile/<int:pk>/', DeleteProfile.as_view(), name='delete_profile'),
    path('deletepost/<int:pk>/', DeletePost.as_view(), name='delete_post'),
    path('younewpost/', NewPost.as_view(), name='newpost_page'),
    path('login/', Login.as_view(), name='login_page'),
    path('about/', TemplateView.as_view(template_name="home/about.html"), name='about'),
    path('contact/', TemplateView.as_view(template_name="home/contact.html"), name='contact'),
    path('', Home.as_view(), name='home_page'),
]

apps/notes/urls.py
from django.urls import path, include
from apps.notes.views import Index, DelelteNote, Complete


app_name = 'notes'

urlpatterns = [
    path('mystatistics/', include('apps.statistics_app.urls', namespace='statistics')),
    path('complete/<int:pk>/', Complete.as_view(), name='complete_page'),
    path('notesdelete/<int:pk>/', DelelteNote.as_view(), name='delete_note'),
    path('', Index.as_view(), name='notes_page'),
]

apps/search/urls.py
from django.urls import path
from apps.search.views import Search

app_name = 'search'


urlpatterns = [
    path('', Search.as_view(), name='search_page'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('notes/', include('apps.notes.urls', namespace='notes')),
    path('search/', include('apps.search.urls', namespace='search')),
    path('admin/', admin.site.urls),
    path('settings/', include('apps.settings_profile.urls', namespace='settings')),
    path('registration/', include('apps.Profile.urls', namespace='profile')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates/backup.html
<div class="btn_back">
    <span onclick="window.history.back()" >back</span>
</div>

apps/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title> GETSWE.COM </title>
    <meta name="viewport" content="width=device-width">
    <link rel="shortcut icon" type="image/icon" href="{% static 'img/favicon.ico' %}"/>
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
    <script src="https://code.jquery.com/jquery-3.2.1.js"></script>
    <script
        src="https://code.jquery.com/ui/1.12.1/jquery-ui.min.js"
        integrity="sha256-VazP97ZCwtekAsvgPBSUwPFKdrwD3unUfSGVYrahUqU="
        crossorigin="anonymous">
    </script>
  </head>
  <body>
    {% block content %}

    {% endblock %}
    <script src="{% static 'js/uploadPreview.js' %}" type="text/javascript"></script>
    <script src="{% static 'js/main.js' %}"></script>
  </body>
</html>

apps/templates/error.html
<div class="error_form">
    <p>Your nickname must be unique. Try another one.</p>
</div>

apps/templates/header.html
{% load static %}
<div class="header">
  <div class="header_container">
    <img class='logo' onclick="window.location.href='/'" src="{% static 'img/logo.png' %}" />
    <form action="{% url 'search:search_page' %}">
      <input type="text" name="q" placeholder="Search ...">
    </form>
    <div class="user_info">
        <!-- <a class="btn_newpost" href="{% url 'notes:notes_page' %}">my notes</a> -->
        <a class="btn_newpost_img" href="{% url 'notes:notes_page' %}">
            <img src="{% static 'img/list.png' %}" alt="">
        </a>
        <a class="btn_newpost_img" href="{% url 'home:newpost_page' %}">
            <img src="{% static 'img/quill-drawing-a-line.png' %}" />
        </a>
        <a class="btn_login" href="{% url 'home:detail_profile' pk=user.profile.pk %}">
        {% if user.profile.avatar %}
            <img class='img_user' src="{{user.profile.avatar.url}}" />
        {% else %}
            <img class="img_user" src="https://www.freeiconspng.com/uploads/no-image-icon-4.png" />
        {% endif %}
      </a>
      <a class="logout_btn" href="{% url 'logout' %}">logout</a>
    </div>
  </div>
</div>

apps/templates/last_subscriptions.html
{% if user %}
<div class="last_notes_container">

    <h6>NOTES</h6>
    {% if profile.my_notes %}
        <p>You have {{profile.my_notes.count}} notes for today.</p>
        <a href="{% url 'notes:notes_page' %}">click</a>
    {% else %}
        <p>You have no notes for today. Create notes for any day.</p>
        <a href="{% url 'notes:notes_page' %}">click</a>
    {% endif %}
</div>
{% endif %}

apps/templates/seccess.html
<div class="seccess_form">

    <p>You are registered, now you can login.</p>

</div>