apps/Profile/urls.py
from django.urls import path, include
from apps.Profile.views import UserRegister

app_name = 'profile'

urlpatterns = [
    path('', UserRegister.as_view(), name='registration_page'),
]

apps/home/urls.py
from django.urls import path, include
from apps.home.views import (
    Home,
    Login,
    DetailProfile,
    NewPost,
    EditPost,
    DeletePost,
    DeleteProfile,
    Subscriptions,
    Unsubscriptions
)
from django.views.generic import TemplateView
from apps.article.views import DetailArticle
from apps.comments.views import DeleteComments

app_name = 'home'

urlpatterns = [
    path('deletecomment/<int:pk>/', DeleteComments.as_view(), name='delete_comment'),
    path('detailarticle/<int:pk>/', DetailArticle.as_view(), name='detail_article'),
    path('unsubscriptions/<int:pk>/', Unsubscriptions.as_view(), name='unsubscriptions_page'),
    path('subscriptions/<int:pk>/', Subscriptions.as_view(), name='subscriptions_page'),
    path('profile/id<int:pk>/', DetailProfile.as_view(), name='detail_profile'),
    path('editpost/<int:pk>/', EditPost.as_view(), name='edit_post'),
    path('deleteprofile/<int:pk>/', DeleteProfile.as_view(), name='delete_profile'),
    path('deletepost/<int:pk>/', DeletePost.as_view(), name='delete_post'),
    path('younewpost/', NewPost.as_view(), name='newpost_page'),
    path('login/', Login.as_view(), name='login_page'),
    path('about/', TemplateView.as_view(template_name="home/about.html"), name='about'),
    path('contact/', TemplateView.as_view(template_name="home/contact.html"), name='contact'),
    path('', Home.as_view(), name='home_page'),
]

apps/search/urls.py
from django.urls import path
from apps.search.views import Search

app_name = 'search'


urlpatterns = [
    path('', Search.as_view(), name='search_page'),
]

apps/settings_profile/urls.py
from django.urls import path
from apps.settings_profile.views import Settings


app_name = 'settings'


urlpatterns = [
    path('profile/id<int:pk>/', Settings.as_view(), name='settings_page'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('notes/', include('apps.notes.urls', namespace='notes')),
    path('search/', include('apps.search.urls', namespace='search')),
    path('admin/', admin.site.urls),
    path('settings/', include('apps.settings_profile.urls', namespace='settings')),
    path('registration/', include('apps.Profile.urls', namespace='profile')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/home/forms.py
from django import forms


class LoginForm(forms.Form):
    username = forms.CharField(label="",required=True,max_length=100)
    password = forms.CharField(label="",required=True,widget=forms.PasswordInput())

    username.widget.attrs.update({'placeholder': 'Username ...'})
    password.widget.attrs.update({'placeholder': 'Password ...'})

apps/home/views.py
import asyncio
from django.shortcuts import render, redirect, reverse
from django.views import View
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic.detail import DetailView
from django.contrib.auth import authenticate, login
from apps.Profile.forms import RegisterForm
from django.contrib.auth.models import User
from apps.Profile.models import Profile
from apps.article.models import Article
from apps.comments.models import Comment
from apps.comments.forms import FormComment
from apps.home.forms import LoginForm
from apps.home.sorted import result_article
# Create your views here.


class Unsubscriptions(LoginRequiredMixin, View):
    ''' DELETE SUBSCRIDE  '''
    def get(self, request, *args, **kwargs):
        current_profile = Profile.objects.get(user=request.user)
        profile_del = Profile.objects.get(pk=kwargs['pk'])
        current_profile.subscriptions.remove(profile_del)
        return HttpResponseRedirect(reverse('home:detail_profile', kwargs={'pk': profile_del.pk}))


class Subscriptions(LoginRequiredMixin, View):
    ''' ADD SUBSCRIBE '''
    def get(self, request, *args, **kwargs):
        current_profile = Profile.objects.get(user=request.user)
        profile = Profile.objects.get(pk=kwargs['pk'])
        current_profile.subscriptions.add(profile)
        current_profile.save()
        return HttpResponseRedirect(reverse('home:detail_profile', kwargs={'pk': profile.pk}))


class DeleteProfile(LoginRequiredMixin, View):
    ''' Delete User and Profile '''
    def get(self, request, *args, **kwargs):
        user = User.objects.get(pk=kwargs['pk'])
        if request.user == user:
            user.delete()
        return redirect('home:home_page')



class DeletePost(LoginRequiredMixin, View):
    ''' Delete Post '''
    def get(self, request, *args, **kwargs):
        article = Article.objects.get(pk=kwargs['pk'])
        article.delete()
        return HttpResponseRedirect(reverse('home:detail_profile', kwargs={'pk': article.author.profile.pk}))


class EditPost(LoginRequiredMixin, View):
    ''' Update post  '''

    def get(self, request, *args, **kwargs):
        article = Article.objects.get(pk=kwargs['pk'])
        if request.user == article.author:
            return render(request, 'home/editpost.html', {'article' : article})
        else:
            return redirect('home:home_page')

    def post(self, request, *args, **kwargs):
        article = Article.objects.get(pk=kwargs['pk'])
        article.text = request.POST.get("edit")
        img = None
        img = request.FILES.get('images') or article.img
        article.img = img
        article.save()
        return HttpResponseRedirect(reverse('home:detail_profile', kwargs={'pk': article.author.profile.pk}))







class NewPost(LoginRequiredMixin, View):
    ''' New post '''

    def get(self, request, *args, **kwargs):
        profile = Profile.objects.get(user=request.user)
        return render(request, 'profile/newpost.html', {'profile': profile})

    def post(self, request, *args, **kwargs):
        article = Article(author=request.user, text=request.POST.get('text'),
                img = request.FILES.get('images') or None)
        article.save()
        return redirect('home:home_page')



# def result_article(profile):
#     ''' Function return subscriptions articles '''
#     # articlesresult = Article.objects.filter(author=[x.user for x in profile.subscriptions.all()])
#     result = []
#     articles = Article.objects.all()
#     for sub in profile.subscriptions.all():
#         for art in articles:
#             if sub.user == art.author:
#                 result.append(art)
#     result+= profile.user.article_set.all()
#     return result



class Home(View):
    ''' Home page class '''
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            profile = Profile.objects.get(user=request.user)
            articles = result_article(profile)
            return render(request, 'home/index.html',
                {'profile': profile, 'articles': articles}
            )
        else:
            return render(request, 'home/guest.html', {})




class DetailProfile(LoginRequiredMixin, View):
    #model = Profile
    login_url = 'home:login_page'
    #template_name = 'home/detail.html'

    def get(self, request, *args, **kwargs):
        #profile_detail = Profile.objects.get(pk=kwargs['pk'])
        try:
            profile_detail = get_object_or_404(Profile, pk=kwargs['pk'])
        except Profile.DoesNotExist:
            raise Http404("No Profile matches the given query.")
        articles = Article.objects.filter(author=profile_detail.user)
        flag = False
        current_user = Profile.objects.get(user=request.user).subscriptions.all()
        if profile_detail in current_user:
            flag = True
        return render(request, 'home/detail.html',
            {'profile_detail': profile_detail, 'articles': articles, 'flag': flag}
        )

    #def get_context_data(self, **kwargs):
        #context = super().get_context_data(**kwargs)
        #object = kwargs['object']
        #context['profile_detail'] = Profile.objects.get(pk=object.user.pk)
        #context['articles'] = Article.objects.filter(author=context['profile_detail'].user)
    #   return context



class Login(View):
    ''' Login User '''

    def get(self, request, *args, **kwargs):
        form = LoginForm()
        return render(request, 'home/login.html', {'form': form})


    def post(self, request, *args, **kwargs):
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user = authenticate(username=username, password=password)
            if user is not None:
                login(request, user)
                return redirect('home:home_page')

            else:
                return redirect('home:login_page')

apps/templates/home/about.html
{% extends 'base.html' %}


{% block content %}
<div class="about_container">
  <p>This is a small blog platform. Aimed at the Scandinavian countries.
  We hope that you will not be upset.
  This is currently a beta version.
  </p>
</div>

{% endblock %}

apps/templates/home/contact.html
{% extends 'base.html' %}


{% block content %}

<div class="contact_container">
  <p>You can contact us at this address.</p>
</div>

{% endblock %}

apps/templates/home/detail.html
{% extends 'base.html' %}



{% block content %}
{% include 'header.html' %}

<div class="detail_container">
  <div class="detail_user_info">
    {% if user == profile_detail.user %}
      <a href="{% url 'settings:settings_page' pk=profile_detail.user.pk %}" class="settings_btn" >settings</a>
    {% endif %}

    {% if user != profile_detail.user %}
        {% if flag %}
            <a href="{% url 'home:unsubscriptions_page' pk=profile_detail.pk %}" class="follow_btn">unsubscribe</a>
        {% else %}
            <a href="{% url 'home:subscriptions_page' pk=profile_detail.pk %}" class="follow_btn">subscribe</a>
        {% endif %}
    {% endif %}
    {% if profile_detail.avatar %}
      <img src="{{profile_detail.avatar.url}}" alt="">
    {% else %}
      <img src="https://www.freeiconspng.com/uploads/no-image-icon-4.png" alt="">
    {% endif %}
    <div class="detail_fullname">
      <h3>{{profile_detail.fullname}}</h3>
      <!--<p>{{profile_detail.fullname}}</p>-->
      {% if profile_detail.description %}
        <span>{{profile_detail.description}}</span>
      {% endif %}
    </div>
  </div>

  <div class="detail_info_post">
    <div class="btn_posts_followers">
      <a class="btn_posts" href="">Posts</a><span>{{profile_detail.count}}</span>
      <a class="btn_subscriptions" href="">subscriptions</a><span>{{profile_detail.count_subscriptions}}</span>
    </div>
    <div class="detail_profile_sub">
        {% if profile_detail.subscriptions.all %}
        <div class="sub_container">
        {% for sub in profile_detail.subscriptions.all %}
            <div class="profile_sub">
                {% if sub.avatar %}
                    <img src="{{sub.avatar.url}}" width="70px" height="70px;" />
                {% else %}
                    <img src="https://www.freeiconspng.com/uploads/no-image-icon-4.png" width="70px" height="70px" alt="">
                {% endif %}
                <a href="{% url 'home:detail_profile' pk=sub.pk %}">{{sub.fullname}}</a>
            </div>
        {% endfor %}
        </div>
        {% else %}
            <h3>NOT SUBSCRIBE.</h3>
        {% endif %}
    </div>
    {% if articles %}
    {% for article in articles %}
      <div class="post_container">
        {% if user == profile_detail.user %}
        <div class="delete_edit_post">
            <a href="{% url 'home:edit_post' pk=article.pk %}">edit</a>
            <a class="delete_btn" href="{% url 'home:delete_post' pk=article.pk %}">delete</a>
        </div>
        {% endif %}
        <div class="post_info">
          {% if profile_detail.avatar %}
            <img src="{{profile_detail.avatar.url}}" width="30px" height="30px" alt="">
          {% else %}
            <img src="https://www.freeiconspng.com/uploads/no-image-icon-4.png" width="30px" height="30px" alt="">
          {% endif %}
          <span class="user_post">{{profile_detail.fullname}}</span>
          <span>{{article.date|date:'m-d-y'}}</span>
        </div>
        {% if article.img %}
            <div class="img_article">
                <img src="{{article.img.url}}" />
            </div>
        {% endif %}
        <p>{{article.text}}<a class="show_view" href="{{  article.get_absolute_url  }}">show view</a> </p>
        <p class="comments">comments : <span class="count_comments_class">{{article.count_comments}}</span></p>
      </div>
    {% endfor %}
    {% else %}
        <div class="not_articles">
            <h3>NO POSTS.</h3>
        </div>
    {% endif %}
  </div>

</div>
{% endblock %}

apps/templates/home/editpost.html
{% extends 'base.html' %}


{% block content %}
{% include 'header.html' %}

<div class="edit_post_container">
    <h3>EDIT POST</h3>
    <form method="POST" enctype="multipart/form-data" > {% csrf_token %}
        <textarea name="edit" required>{{article.text}}</textarea>
        {% if article.img  %}
            <!--<span id="clearedit">Clear</span>-->
            <img width="100%"  id="imgedit" src="{{article.img.url}}" />
            <label class="fileContaineredit">
                newphoto
                <input  id='file_edit' type="file" name="images" value="" />
            </label>
        {% else %}
            <img id='new_img_edit' width="100%"  src="#" />
            <label class="fileContaineredit">
                photo
                <input  id='newfile_edit' type="file" name="images" value="" />
            </label>
        {% endif %}
        <button type="submit" name="button">EDIT</button>
    </form>
</div>
<script type="text/javascript">

    $(function(){
        //



        $('#new_img_edit').hide();

        function newReadURL(input) {
             if (input.files && input.files[0]) {
                     var reader = new FileReader();
                     reader.onload = function(e) {
                         $('#new_img_edit').attr('src', e.target.result);
                     }
                     reader.readAsDataURL(input.files[0]);
                 }
             }


        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#imgedit').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $('#file_edit').change(function(){
            readURL(this);
        });

        $('#newfile_edit').change(function(){
            newReadURL(this);
            $('#new_img_edit').show('slow');
        });

    });

</script>
{% endblock  %}

apps/templates/home/guest.html
{% extends 'base.html' %}
{% load static %}

{% block content %}



<div class="guest">
  <img src="{% static 'img/bg.jpg' %}" />
  <div class="guest_container">
    <h3>Welcome to the Swedish blogging platform. This is a test version but you can try to enter or register.</h3>
    <a href="{% url 'home:login_page' %}"> LOGIN </a><br/>
    <a href="{% url 'profile:registration_page' %}"> REGISTRATION </a>
  </div>
</div>

<div class="btn_contact">

  <a href="{% url 'home:about' %}">about</a>
  <a href="{% url 'home:contact' %}">contact</a>

  <p>&copy; 2019 <p>

</div>


{% endblock %}

apps/templates/home/index.html
{% extends 'base.html' %}



{% block content %}
{% include 'header.html' %}
<div class="main_container">
{% include 'last_subscriptions.html' %}
  <div class="main_user_info">
    {% if profile.avatar %}
        <img src="{{profile.avatar.url}}" />
    {% else %}
        <img src="https://www.freeiconspng.com/uploads/no-image-icon-4.png" />
    {% endif %}
    <div class="user_info">
      <a href="{% url 'home:detail_profile' pk=user.profile.pk %}">{{profile.fullname}}</a>
      <!-- <p class="full_name">{{profile.fullname}}</p> -->
    </div>

    <div class="other_info">
      <span>{{profile.count}}</span>
      <p>Posts</p>
      <span>{{profile.count_subscriptions}}</span>
      <p>subscriptions</p>
    </div>
  </div>
  {% if articles %}
  {% for art in articles %}
    <div class="article_main">
        {% if user == art.author %}
        <div class="delete_edit_post">
            <a href="{% url 'home:edit_post' pk=art.pk %}">edit</a>
            <a class="delete_btn" href="{% url 'home:delete_post' pk=art.pk %}">delete</a>
        </div>
        {% endif %}
        <div class="article_info_user">
            {% if art.author.profile.avatar %}
                <img src="{{art.author.profile.avatar.url}}" width="40px" height="40px" />
            {% else %}
                <img src="https://www.freeiconspng.com/uploads/no-image-icon-4.png" width="40px" height="40px" />
            {% endif %}
            <a href="{% url 'home:detail_profile' pk=art.author.profile.pk %}">{{art.author.profile.fullname}}</a>
            <span>{{art.date|date:'m-d-y'}}</span>
        </div>
        {% if art.img %}
            <div class="img_article">
                <img src="{{art.img.url}}" />
            </div>
        {% endif %}
        <p>{{art.text}} <a class="show_view" href="{{  art.get_absolute_url  }}">show article</a></p>
        <p class="comments">comments : <span class="count_comments_class">{{art.count_comments}}</span></p>
    </div>
  {% endfor %}
  {% else %}
    <div class="not_articles">
        <h3>Try to find interesting articles and subscribe to interesting people.</h3>

        <form action="{% url 'search:search_page' %}">
            <input type="text" name="q" value="" placeholder="Search ...">
        </form>
    </div>
  {% endif %}
</div>

{% endblock %}

apps/templates/home/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}



<div class="guest">
  <img src="{% static 'img/bg.jpg' %}" />
  <div class="login_container">
    <h3> Enter login and password. And then you will enter. </h3>
    <form method="POST"> {% csrf_token %}
      {{form.as_p}}
      <button type="submit" name="button">login</button>
    </form>
  </div>
</div>

<div class="btn_contact">

  <a href="{% url 'home:about' %}">about</a>
  <a href="{% url 'home:contact' %}">contact</a>

  <p>&copy; 2019 <p>

</div>


{% endblock %}