apps/Profile/urls.py
from django.urls import path, include
from apps.Profile.views import UserRegister

app_name = 'profile'

urlpatterns = [
    path('', UserRegister.as_view(), name='registration_page'),
]

apps/home/urls.py
from django.urls import path, include
from apps.home.views import (
    Home,
    Login,
    DetailProfile,
    NewPost,
    EditPost,
    DeletePost,
    DeleteProfile,
    Subscriptions,
    Unsubscriptions
)
from django.views.generic import TemplateView
from apps.article.views import DetailArticle
from apps.comments.views import DeleteComments

app_name = 'home'

urlpatterns = [
    path('deletecomment/<int:pk>/', DeleteComments.as_view(), name='delete_comment'),
    path('detailarticle/<int:pk>/', DetailArticle.as_view(), name='detail_article'),
    path('unsubscriptions/<int:pk>/', Unsubscriptions.as_view(), name='unsubscriptions_page'),
    path('subscriptions/<int:pk>/', Subscriptions.as_view(), name='subscriptions_page'),
    path('profile/id<int:pk>/', DetailProfile.as_view(), name='detail_profile'),
    path('editpost/<int:pk>/', EditPost.as_view(), name='edit_post'),
    path('deleteprofile/<int:pk>/', DeleteProfile.as_view(), name='delete_profile'),
    path('deletepost/<int:pk>/', DeletePost.as_view(), name='delete_post'),
    path('younewpost/', NewPost.as_view(), name='newpost_page'),
    path('login/', Login.as_view(), name='login_page'),
    path('about/', TemplateView.as_view(template_name="home/about.html"), name='about'),
    path('contact/', TemplateView.as_view(template_name="home/contact.html"), name='contact'),
    path('', Home.as_view(), name='home_page'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('notes/', include('apps.notes.urls', namespace='notes')),
    path('search/', include('apps.search.urls', namespace='search')),
    path('admin/', admin.site.urls),
    path('settings/', include('apps.settings_profile.urls', namespace='settings')),
    path('registration/', include('apps.Profile.urls', namespace='profile')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('apps.home.urls', namespace='home')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/Profile/models.py
from django.db import models
from django.db.models import signals
from django.dispatch import receiver
from django.contrib.auth.models import User
from django.db.models.signals import post_save, post_delete, pre_save
from django.dispatch import receiver
from apps.article.models import Article
from apps.notes.models import Note
import datetime
import os

# Create your models here.



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    description = models.TextField(blank=True)
    avatar = models.ImageField(upload_to='avatar/', blank=True, null=True)
    subscriptions = models.ManyToManyField('self', related_name="Subscriptions", symmetrical=False)
    timestamp = models.DateTimeField(auto_now_add=True)


    class Meta:
        ordering = ['-timestamp']


    @property
    def fullname(self):
        return f"{self.user.first_name} {self.user.last_name}"

    def __str__(self):
        return f"Profile : {self.user.username}"

    def count(self):
        return Article.objects.filter(author=self.user).count()

    def count_subscriptions(self):
        return self.subscriptions.count()


    def last_five_sub(self):
        return self.subscriptions.all()


    def my_notes(self):
        notes = Note.objects.filter(user=self.user).filter(
            timestamp=datetime.datetime.now().date()
        )

        return notes






@receiver(pre_save, sender=Profile)
def auto_delete_pre_save(sender, instance, **kwargs):
    if not instance.avatar:
         return False
    old_file = sender.objects.get(user=instance.user).avatar or None

    if old_file:
        if not old_file == instance.avatar:
            if os.path.isfile(old_file.path):
                os.remove(old_file.path)


@receiver(post_delete, sender=Profile)
def my_signal(sender, instance, **kwargs):
        if instance.avatar:
            if os.path.isfile(instance.avatar.path):
                os.remove(instance.avatar.path)
        else:
            print('NOT IMG')

apps/Profile/forms.py
from django import forms


class RegisterForm(forms.Form):
    username = forms.CharField(label='',required=True,max_length=100)
    first_name = forms.CharField(label='', max_length=100)
    last_name = forms.CharField(label='', max_length=100)
    password = forms.CharField(label='',required=True,widget=forms.PasswordInput())


    username.widget.attrs.update({'placeholder': 'Username* ...', 'class' : 'registration_username_form',
                                    'autocomplete' : 'off',
    })
    password.widget.attrs.update({'placeholder': 'Password* ...', 'class' : 'registration_password_form',
                                    'autocomplete' : 'off',
    })
    first_name.widget.attrs.update({'placeholder': 'First Name* ...', 'class' : 'registration_firstname_form',
                                    'autocomplete' : 'off',
    })
    last_name.widget.attrs.update({'placeholder': 'Last Name* ...', 'class' : 'registration_lastname_form',
                                    'autocomplete' : 'off',
    })

apps/Profile/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.views import View
from apps.Profile.forms import RegisterForm
from django.contrib.auth.models import User
from apps.Profile.models import Profile
from apps.statistics_app.data.data import write_new_person

# Create your views here.

class UserRegister(View):
    ''' Registration new user and profile '''

    def get(self, request, *args, **kwargs):
        form = RegisterForm()
        return render(request, 'profile/registration.html', {'form': form})


    def post(self, request, *args, **kwargs):

        username = request.POST.get('username')
        password = request.POST.get('password')
        firstname = request.POST.get('firstname')
        lastname = request.POST.get('lastname')

        user = User.objects.create_user(username=username)
        user.first_name = firstname
        user.last_name = lastname
        user.set_password(password)
        try:
            user.save()
        except Exception:
            return HttpResponse('error python')
        profile = Profile(user=user)
        profile.save()
        write_new_person(profile.pk, profile.user.username)
        return HttpResponse('success python')

apps/templates/profile/newpost.html
{% extends 'base.html' %}


{% block content %}
{% include 'header.html' %}
{% include 'backup.html' %}
<div class="new_post_container">
    {% if profile.avatar %}
        <img src="{{profile.avatar.url}}" width="50px" height="50px" />
    {% else %}
        <img src="https://www.freeiconspng.com/uploads/no-image-icon-4.png" width="50px" height="50px" />
    {% endif %}
    <p>{{profile.fullname}}</p>

    <form method="POST" enctype="multipart/form-data">{% csrf_token %}
        <textarea required placeholder="Your text ..." name="text"></textarea>
        <span id="clear">Clear</span>
        <img id='img' src="#" />
        <label class="fileContainer">
            photo
            <input id="imgInp" name='images' type="file" >
        </label>
        <button type="submit" name="button">ADD</button>
    </form>
</div>

<script type="text/javascript">
    $(function(){
        $('#clear').hide();
        $('#img').hide();
        function readURL(input) {
            if (input.files && input.files[0]) {
                var reader = new FileReader();
                reader.onload = function(e) {
                    $('#img').attr('src', e.target.result);
                }
                reader.readAsDataURL(input.files[0]);
            }
        }

        $("#imgInp").change(function() {
            readURL(this);
            $('#img').show('slow');
            $('#clear').show();
        });

        $("#clear").click(function () {
            $("#imgInp").val("");
            $('#clear').hide();
            $('#img').hide('slow');
        });

    })



</script>

{% endblock %}

apps/templates/profile/registration.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'seccess.html' %}
{% include 'error.html' %}
<div class="guest">
  <img src="{% static 'img/bg.jpg' %}" />
  <div class="registration_container">
    <h3> Sign up to the platform and blog. </h3>
    <form class="form_registation" method="POST"> {% csrf_token %}
      {{form.as_p}}
      <button type="submit" name="button">register</button>
    </form>
  </div>
</div>


<div class="btn_contact">

  <a href="{% url 'home:about' %}">about</a>
  <a href="{% url 'home:contact' %}">contact</a>

  <p>&copy; 2019 <p>

</div>
<script src="{% static 'js/registration.js' %}" type="text/javascript"></script>
{% endblock %}

apps/templates/profile/settings.html
{% extends 'base.html' %}


{% block content %}

{% include 'header.html' %}
{% include 'backup.html' %}
<div class="settings_container">

  <h3> You can change some settings.</h3>


  <form method="POST" enctype="multipart/form-data">{% csrf_token %}
      <label>New photo</label>
      <div id="image-preview">
          <label for="image-upload" id="image-label">Choose File</label>
          <input type="file" name="image" id="image-upload" />
      </div>
      <label>Username</label>
      <input type="text" name="username" value="{{profile.user.username}}">
      <label>First name</label>
      <input type="text" name="firstname" value="{{profile.user.first_name}}">
      <label>Last name</label>
      <input type="text" name="lastname" value="{{profile.user.last_name}}">
      <label>Description</label>
      <textarea name="description" >{{profile.description}}</textarea>

    <button type="submit" name="button">UPDATE</button>

  </form>


    <div class="delete_profile_btn">
        <a href="{% url 'home:delete_profile' pk=profile.user.pk %}">delete profile</a>
    </div>

</div>

{% endblock %}